### ISSUE TITLE
Animated Hamburger Menu Icon

### ISSUE THREAD

**Issue by rugulous** [BritishYouthBandAssociation/Style#27]
We need an icon for our menu, preferably one that animates between hamburger and cross

**Comment by matt-fidd** [comment]
Ooo I've got something for that 😉

**Comment by rugulous** [comment]
Oooh go on then... ;)

**Comment by rugulous** [comment]
Thinking about this more...

From previous discussions, we would prefer **CSS-only** solutions.

I've done a bit of research and the way I was planning on implementing this requires JS - however, it *is* possible to do it with just CSS, a hidden checkbox, and a label (+ pseudo-elements).

@matt-fidd before I go further down the rabbit hole, how does your one work?
