### ISSUE TITLE
Long button is too long

### ISSUE THREAD

**Issue by rugulous** [BritishYouthBandAssociation/Style#30]
The buttons styled with `.btn-long` are *too* long and do not match up with other full-width elements in their container

![image](https://user-images.githubusercontent.com/13632306/158148168-00b5fd37-420f-45f0-8dc0-163485fc1fe1.png)

**Comment by rugulous** [comment]
On further investigation, I am an idiot!

`.input` has a margin of `$spacer` whereas the buttons do not have a margin - this is the "too long" bit!

Guess we need to decide whether we want to add margin to everything in a form, or to remove the margin from `.input` - @matt-fidd what do you think?

**Comment by matt-fidd** [comment]
Hrmmm, my personal opinion is to treat spacing as if whatever the element is, is text. 

So in this case you wouldnt add margin to a text element, you'd instead add padding to it's container. 

Keeps it more flexible too - so I vote to scrap the margin (in the x axis) from the inputs and replace it with whatever padding we want on it's container.
